const BASE_API_URL = 'https://api.tp-cloud.xyz'

const CLOUD_FUNCTION_URL = {
	ADD_USER_FILE: 'add-user-file',
	DELETE_USER_SUBJECT: 'delete-user-subject',
	GET_ALL_SUBJECTS: 'get-all-subjects',
	GET_USER_SUBJECTS: 'get-user-subjects',
	GET_USER_FILES: 'get-user-files',
	LOGIN: 'login',
	POST_USER: 'post-user',
	POST_USER_SUBJECT: 'post-user-subject'
}

export const REQUESTS_URL = {
	ADD_USER_FILE_URL: `${BASE_API_URL}/${CLOUD_FUNCTION_URL.ADD_USER_FILE}`,
	DELETE_USER_SUBJECT_URL: `${BASE_API_URL}/${CLOUD_FUNCTION_URL.DELETE_USER_SUBJECT}`,
	GET_ALL_SUBJECTS_URL: `${BASE_API_URL}/${CLOUD_FUNCTION_URL.GET_ALL_SUBJECTS}`,
	GET_USER_SUBJECTS_URL: `${BASE_API_URL}/${CLOUD_FUNCTION_URL.GET_USER_SUBJECTS}`,
	GET_USER_FILES_URL: `${BASE_API_URL}/${CLOUD_FUNCTION_URL.GET_USER_FILES}`,
	LOGIN_URL: `${BASE_API_URL}/${CLOUD_FUNCTION_URL.LOGIN}`,
	POST_USER_URL: `${BASE_API_URL}/${CLOUD_FUNCTION_URL.POST_USER}`,
	POST_USER_SUBJECT_URL: `${BASE_API_URL}/${CLOUD_FUNCTION_URL.POST_USER_SUBJECT}`
}